# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado en')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo?')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado?')),
                ('tipoTrans', models.CharField(choices=[('V', 'Venta'), ('A', 'Alquiler')], max_length=1, verbose_name='Tipo de Transacción')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('numero', models.PositiveSmallIntegerField(default=0, verbose_name='Número')),
                ('terreno', models.PositiveIntegerField(default=0, verbose_name='Terreno')),
                ('unidad', models.CharField(choices=[('M', 'm²'), ('H', 'Ha')], max_length=1, verbose_name='Unidad')),
                ('habitaciones', models.PositiveSmallIntegerField(verbose_name='Habitaciones')),
                ('cochera', models.PositiveSmallIntegerField(verbose_name='Cochera')),
                ('pileta', models.BooleanField(verbose_name='Pileta')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('actualizadoPor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ('-publicado',),
                'verbose_name': 'Anuncio',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='TipoDomicilio',
            fields=[
                ('tipo', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('tipo', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Tipo Propiedades',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anuncios.Ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='creadoPor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='anuncios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipoDom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anuncios.TipoDomicilio', verbose_name='Tipo de Domicilio'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipoProp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anuncios.TipoPropiedad', verbose_name='Tipo de Propiedad'),
        ),
    ]
