# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='kilometro',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Km'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='domicilio',
            field=models.CharField(max_length=50, verbose_name='Calle'),
        ),
    ]
