# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20170306_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='domicilio',
            field=models.CharField(max_length=50, verbose_name='Domicilio'),
        ),
    ]
